en = [""]
fr = ["aire ","l'autoroute ","autoroute ","boulevard périphérique extérieur","boulevard périphérique intérieur","allee ","grand'rue","grand-rue","rue ","grande route ","grande rue ","bois ","bois-","avenue ","allée ","allées ","place ","vieux chemin ","chemin rural ","chemin ","cheminement ","chemins ","contour ","cité ","corniche ","quai ","pont ","pont au ","-straße"," straße","straße","digue ","escaliers ","imp. ","espace ","esplanade ","galerie ","hameau ","port ","route ","descente ","boulevard ","rond-point ","giratoire ","impasse ","impasses ","jardin ","j'sais pas ","tunnel ","fort ","cours ","côte ","autoroutier ","villa ","square ","echangeur ","square"," voie ","arbe ","chaussée ","sentier ","ruelle ","clos ","station ","passage ","barrière ","bas-","bas ","basse-","basse ","basses-","basses ","baty ","cour ","drève ","porte ","périphérique ","résidence ","promenade ","venelle ","via ","via ferrata ","viaduc ","voie centrale ","voie communale ","voie ","zone artisanale ","zone d'attente "]

de = [" allee","-allee","allee"," abstieg ","ausfahrt ","ausstieg ","forststraße ","forstweg ","berggasse "," bergstraße","steinweg ","fußweg ","bahnhofstraße","friedhofstraße","hofstraße","wegstraße"," straße","-straße","straße","starße"," gasse","gasse"," damm","chaussee","alte ","alter ","-klettersteig","  klettersteig","steigweg","steig","talweg","kreuzung"," brücke","brücke"," strasse","strasse","alte"," platz","-platz","-str.","-ring"," ring","-bouldervard"," boulevard","boulevard"," hof","-hof","innere ","lange "," bogen","mittlerer ","mittlere ","mittleres ","-radweg","talstrasse","neuer ","neue ","neues ","obere ","oberer ","oberes ","rastplatz ","ratstätte ","zustieg "," zustieg","-stiege","untere ","unterer ","unteres ","äußere "," autobahn", " bahnhof", " bahnrad","hofzufahrtsweg ","hofzufahrt ","zufahrt zum ","zufahrt zur ","zufahrtsweg ","zufahrts ","zufahrt ","zugang ","-radwanderweg","-wanderweg"," weg","-weg","weg","-promenade"]


nl = ["-laan"," laan","laan ","laan","-straat","gang","straat","plein"," plein","park ter", "park ten","park ","park","baan ","baan","berg ","hof van ","hof ten","hof ter","hof ","hof","steenweg op ","steenweg van ", "steenweg","sesteenweg","steenweg","pad ","pad","vest","dreef","viaduct","poort","veld ","veld","plaats","lei","kaai","binnenring-","wegel ","weg naar ","weg ","weg","huis ten","huis ter","kade","steegje","steeg","singel","brug"," brug","brug","stoep","dijk","tunnel"]

pt = ["acesso ","aeroporto ","alameda ","antiga ","autoestrada ","autovia ","avenida general ","avenida ","azinhaga","bairro ","baragem ","beco ","cai ","cais ","calle ","calcada ","caminho municipal ","caminho ","camino ","campo ","canada ","carretera ","circular interna ","circular regional interior ","circular sul ","circular ","couraca ","escadaria ","escadas ","escadinhas ","esplanada ","estrada intermunicipal ","estrada principal ","estrada municipal ","estrada regional ","estrada ","estradao ","jardim ","ladeira ","largo ","levada ","passeio ","ponte ","praceta ","praca ","praca general ","rampa ","rotunda ","rua ","rua central ","rua cidade ","travessa ","travessia ","tunel ","trilho ","urbanizacao ","variante ","vereda ","via ","vidauto ","viela nova ","viela ","villa ","do ","de ","da ","das ","dos "]

es = ["lateral avinguda ","gran avinguda ","avinguda central ","avinguda generalitat ","avinguda ","acceso a ","a la ","acceso a parking ","acceso colegio ","accès al camí ","acceso cueva ","acceso centro ","acceso sur ","accès ","accés ","accesu ","acceso ","accs ","a travessia ","acera ","alameda ","aldea ","altozano ","andador ", "antigua carretera ","aparcamiento ","aproximacion barranco ","transversal ","trav. ","travesa avenida ","bicisenda bosquesur - ruta ","bus-vao","arco ","atrio ","autovía ", "av. ","avda ","avenida ","barrio ","carretera ","crta. ","calle arcos ","call ","calle eras ","calle ","calla ","camino ","camiño ","cañada ","carrer ","carril ","costera ", "cordel ","cuesta ","enlace ","estrada ","huerta ","huertos ","glorieta ","grupo ","monasterio ","parc ","parking ","parque ","pasaje ","paseo ","pas ","pasarela ","passatge ","passeig ","placeta ","plaza ","plazuela ","plaça ","praza ","puente ","pujada ","pza. ","ramal ","rambla ","raval ","riera ","rincón ","ronda ","rotonda ","rua ","ruta ","rúa ","sendero ","senda ","subida ","travesía calle ","alle ","travesía camino ","travesía ","travesia ","travessia ","travesera ","transversal ","travesa ","travessera ","tunel ","urbanización ","urdaneta ","vereda ","vía verde  ","vía "," kalea"," plaza"," bidea"," bidegorria"," etorbidea"," zeharbidea","del alcalde ","costa ","del ","des ","der ","de los ","de ","do ","en ","l'"]


it = ["autodromo ","autostrada ","bastioni ","calle ","campiello ","campo ","cavalcavia ","circonvallazione ","constrada ","corso ","corte ","fondamenta ","fondamente ","galleria ","largo ","località ","lungarno ","lungo ","lungofiume ","lungomare ","lungotevere ","lungotronto ","mura ","passaggio ","passo ","passo via ","pizza ","piazzale ","piazzella ","piazzetta ","pista ciclabile ","ponte ","raccordo autostrodale ","raccordo ","ramo primo","ramo secondo ","ramo ","rio tera'","rio terra ","rio terrà ","rio terà ","riva ","riviera ","rotonda ","salita superiore ","salita ","salizada ","scala ","sentioro ","sotoportego ","strada comunale ","strada militare ","strada provinciale ","strada vicinale ","strada ","superstrada ","tangenziale ","via nazionale ","via ","viale ","vico ","vicolo "]
