SELECT * FROM sbs_classification_noduplicate
where char_length(name)=1 or char_length(name)=2 
or name REGEXP '^ [0-9]' or name REGEXP '[a-z][0-9]' or name REGEXP '[=>]' 
or name REGEXP '[!]' or name REGEXP '[?]' or name REGEXP '^see - ' 
or name REGEXP '[«]' or name REGEXP '^ -' or name REGEXP '^ nr.' 
or name REGEXP '^ [a-z].$' or name REGEXP '^ [a-z]..$' 
or name REGEXP '^ [(]' or name REGEXP '["]' or name REGEXP 'a [0-9]' or name REGEXP '^- ' 
or name REGEXP '^verbindungs' or name REGEXP '^trift ' or name REGEXP '^tl ' 
or name REGEXP '^tiefgarage 'or name REGEXP '^süd ' or name REGEXP '^str. '
or name REGEXP '^stazionne ' or name REGEXP '^statale [0-9]' or name REGEXP 'spur '
or name REGEXP 'sportplatz ' or name REGEXP 'si, ' or name REGEXP '^sentiero [0-9]'
or name REGEXP '^sentiero $' or name REGEXP 'sente rurale' or name REGEXP 'seepark '
or name REGEXP '^see ' or name REGEXP '^scs ' or name REGEXP '^schi '
or name REGEXP '^sat ' or name REGEXP '^rã' or name REGEXP '^rampe [0-9]'
or name REGEXP '^rampe $' or name REGEXP '^r [0-9]' or name REGEXP '^privé '
or name REGEXP '^piste [0-9]' or name REGEXP '^n°' or name REGEXP 'no_name'
or name REGEXP '^no name' or name REGEXP '^nationale' or name REGEXP '^n [0-9]'
or name REGEXP '^kn ' or name REGEXP '^kante ' or name REGEXP '^kanal '
or name REGEXP '^iz-nö-süd ' or name REGEXP '^ix  ' or name REGEXP '^ixme '
or name REGEXP 'heime, ' or name REGEXP '^gewerbepark ' or name REGEXP '^gewerbegebiet '
or name REGEXP '^gewerbezone' or name REGEXP '^gewerbe ' or name REGEXP '^communal '
or name REGEXP '^cai ' or name REGEXP '^c.a.i ^' or name REGEXP '^av '
or name REGEXP '^autostradale ' or name REGEXP '^autobahnzubringer' or name REGEXP '^auto-'
or name REGEXP '^akaziensiedlung';